### ISSUE TITLE
Consider merged-miners as stakeholders

### ISSUE THREAD

**Issue by monsterbitar** [ActorForth/Auction-Protocol#4]
It has come to my attention, that merge-mining miners are one stakeholder to consider.

We should look into what merged miners exist, and reach out to them.

**Comment by scherrey** [comment]
Same answer re:wallets but doubly so. I don't know who any miners are or their contact info. Appreciate any referrals that I can follow up on.

**Comment by monsterbitar** [comment]
I don't have these answers, but someone is bound to have them.

I would ask around, in developer or infrastructure groups, on the chip discussion etc.

**Comment by scherrey** [comment]
Have added request for this category to the CHIP and am seeking out comment.
