### ISSUE TITLE
Consider wallets as stakeholders

### ISSUE THREAD

**Issue by monsterbitar** [ActorForth/Auction-Protocol#5]
It has come to my attention that there are wallets that are or want to use OP_RETURN based protocols and that there might be issues or difficulties to understand in relation to their implementations.

We should reach out to the known wallets and ask them what their feedback is.

**Comment by scherrey** [comment]
Happy to do so - and have for the ones I'm aware of without a response - but I don't know how to contact them or necessarily who they all are. What are the wallets we should reach out to (and do you have good contact info)?

**Comment by monsterbitar** [comment]
I don't know who they all are, but when I reached out in order to talk about cashaccounts, I made a list of all the wallets I could find, then made github/gitlab issues when I could find a repository, and sent emails when I couldn't, and I documented that process.

Even if you don't get any feedback, you should still include that you've reached out and that you haven't received any feedback.

For a chip that targets early activation, it would be good to get this information onto the chip ASAP.

I don't have this on my chips today, but that is because I'm targetting 2022 and want to make more efforts to reach out, and I have the time.

**Comment by scherrey** [comment]
Have added requests for commentary from these entities to the CHIP and am seeking out comments.
